### ISSUE TITLE
Rewirting of URLs with parameters 

### ISSUE THREAD

**Issue by lefevred** [KIMB-technologies/Radio-API#48]
There is an issue with the rewriting of URLs. I'm using lighttpd, and rewrite works fine.

But, the incoming URLs are like these :
 /setupapp/fs/asp/BrowseXML/loginXML.asp?token=0
/setupapp/fs/asp/BrowseXML/Search.asp?sSearchtype=3&Search=8641682810150088&mac=&dlang=eng&fver=7

The rewrite says : rewrite ^(.*)$ /index.php?uri=$1 last;

but in such a case, that would means that the final url has 2  ?  in it : 
/index.php**?**uri=/setupapp/fs/asp/BrowseXML/loginXML.asp**?**token=0

which obviously cannot work.
How to make this work ?

**Comment by lefevred** [comment]
interesting, trying the second option, I get error 500 :(
xx.xx.xx.xx pri.logon.wifiradiofrontier.com - [16/Feb/2024:18:03:42 +0100] "GET /setupapp/fs/asp/BrowseXML/loginXML.asp?token=0 HTTP/1.0" **500** 0 "-" "FS NS/1.0"
xx.xx.xx.xx pri.logon.wifiradiofrontier.com - [16/Feb/2024:18:03:42 +0100] "GET /setupapp/fs/asp/BrowseXML/loginXML.asp?token=0 HTTP/1.0" **500** 0 "-" "FS NS/1.0"

Is there a way to find out in PHP what is generating this 500 ?

and then http 303 

xx.xx.xx.xx pri.logon.wifiradiofrontier.com - [16/Feb/2024:18:03:42 +0100] "GET /setupapp/fs/asp/BrowseXML/Search.asp?sSearchtype=3&Search=a680a4929eb0d0a25ee9782d39aebe3e&mac=&dlang=eng&fver=7 HTTP/1.0" **303** 0 "-" "FS NS/1.0"
xx.xx.xx.xx radio.web.ui - [16/Feb/2024:18:03:42 +0100] "GET /gui/view.php?redirFromIndex HTTP/1.0" 200 2300 "-" "FS NS/1.0"

**Comment by kimbtech** [comment]
Hi,

Lighttpd or PHP fpm should create some PHP error logs. But the location depends on the setup.
You may also check the [troubleshooting](https://github.com/KIMB-technologies/Radio-API/blob/master/Setup.md#troubleshooting) section of Radio-API.

I just tried to run Radio-API via Lighttpd, for me url rewriting works with this line:
`url.rewrite-if-not-file = ( "[^\/](\?.*)$" => "/index.php?uri=${url.path}&${url.query}" )`

---
Just more info about my test, I used a Docker container with Lighttpd besides one with PHP fpm:

```yml
version: "2"

services:
  server:
    image: jitesoft/lighttpd:latest-cgi
    restart: "no"
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - SERVER_NAME=localhost
      - SERVER_ROOT=/var/www/html
      - CONFIG_FILE=/etc/lighttpd/lighttpd.conf
      - SKIP_HEALTHCHECK=true
      - CGI_HOST=phpfpm
      - CGI_PORT=9000
      - CHECK_LOCAL=enable
      - CGI_FILE_EXT=.php
    volumes:
      - ./php/:/var/www/html/ # just mount Radio-API from the Radio-API Source
      - ./urlrewrite.conf:/etc/lighttpd/conf.d/urlrewrite.conf 
    depends_on:
      - phpfpm
  phpfpm:
    image: php:8-fpm-alpine
    restart: "no"
    volumes:
      - ./php/:/var/www/html/

```

Whereas `urlrewrite.conf` only contained one like
 ```
 url.rewrite-if-not-file = ( "[^\/](\?.*)$" => "/index.php?uri=${url.path}&${url.query}" )
 ```
