### ISSUE TITLE
Cannot get the list to work

### ISSUE THREAD

**Issue by rhaamo** [KIMB-technologies/Radio-API#68]
**Radio-API Installation**
- Version of Radio-API: `kimbtechnologies/radio_api:latest`
- Installation mode: Docker
- DNS redirect via: Radio-DNS
- Radio vendor: Philips TAPR802
- Usage of reverse proxy: no
- Does another radio use your installation of Radio-API: no

**Describe the Issue**  
I have changed the DNS in the radio to point to a dedicated VM with Radio-xxx stuff, the API and DNS are running inside docker with this docker-compose file:
```yaml
services:
  radio_api:
    image: kimbtechnologies/radio_api:latest
    container_name: radio_api
    restart: always
    ports:
      - "80:80" # make sure, Radio-API is avaliable at port 80
    volumes:
      - ./data/:/php-code/data/ # directory storing data, cache, and setting od Radio-API
      - ./media/:/php-code/media/ # directory storing images for stations
    environment:
      - DEV=dev
      - CONF_DEV=dev
      - CONF_DOMAIN=http://192.168.10.134/ # the domain where the system is hosted
      # - CONF_RADIO_DOMAIN=http://hama.wifiradiofrontier.com # different domain to use for connections of the radio (if set CONF_DOMAIN is for GUI)
      - CONF_ALLOWED_DOMAIN=all # allowed ips for access, list of DynDNS domainnames (divided by ','), or 'all' to allow all ips
      - CONF_SHUFFLE_MUSIC=true # random shuffle music in nextcloud radio stations
      - CONF_CACHE_EXPIRE=1200 # cache expire time of ips, podcasts, ...
      - CONF_USE_JSON_CACHE=false # set to 'true' to disable redis cache and use a simple file-based cache
      - CONF_REDIS_HOST=redis # the redis hostname
      # - CONF_REDIS_PORT=6379 # default 6379
      # - CONF_REDIS_PASS= # default no auth
      - CONF_STREAM_JSON=false # to disable or an url where to fetch list of own streams, e.g., http://stream.example.com/list.json
      # - CONF_LOG_DIR= # set a custom directory for log files (defaults to ./data/)
      # - CONF_IM_EXPORT_TOKEN= # define a token for use with the im-, export web interface at ./gui/im-export.php
      - CONF_USE_LOGO_CACHE=true # cache logos (make them accessible without ssl and convert svgs to pngs for the radio, stores files in ./media/)
      # - CONF_FAVORITE_ITEMS=Radio,Radio-Browser # define favorite items, which will be listed first on radio
    depends_on:
      - redis

  # remove the following part, if 'CONF_USE_JSON_CACHE=true', i.e., redis is not used!
  redis:
    image: redis:alpine
    container_name: radio_api_redis
    restart: always
    #volumes:
    #  - ./redis/:/data # redis is used as cache, so all data can be loaded from json files saved in radio_api

  radio_dns:
    image: kimbtechnologies/radio_dns
    container_name: radio_dns
    restart: always
    network_mode: host
    environment:
      - SERVER_BIND=0.0.0.0
      - SERVER_PORT=53
      - SERVER_UPSTREAM=192.168.10.1
      - RADIO_IP=192.168.10.134
      - ALLOWED_DOMAIN=all
```

In the docker-compose logs I do see the startup:
```
radio_api_redis  | blah blah etc.
radio_api        | =================================
radio_api        | Key           : Value
radio_api        | ---------------------------------
radio_api        | type          : all
radio_api        | =================================
radio_api        |
radio_api        | Load (Un-)Read:
radio_api        | Load RadioBrowser:
radio_api        | [15-Jan-2025 10:34:38] NOTICE: fpm is running, pid 14
radio_api        | [15-Jan-2025 10:34:38] NOTICE: ready to handle connections
```

But when I do try to load the stations list, I only see:
```
radio_dns        | 2025-01-15 10:41:25 [DNSHandler:Resolver] Request: [192.168.10.98:55749] (udp) / 'airable.wifiradiofrontier.com.' (A)
radio_dns        | 2025-01-15 10:41:25 [DNSHandler:Resolver] Reply: [192.168.10.98:55749] (udp) / 'airable.wifiradiofrontier.com.' (A) / RRs: A
radio_dns        | 2025-01-15 10:41:25 [DNSHandler:Resolver] Request: [192.168.10.98:55750] (udp) / 'airable.wifiradiofrontier.com.' (A)
radio_dns        | 2025-01-15 10:41:25 [DNSHandler:Resolver] Reply: [192.168.10.98:55750] (udp) / 'airable.wifiradiofrontier.com.' (A) / RRs: A
radio_dns        | 2025-01-15 10:41:25 [DNSHandler:Resolver] Request: [192.168.10.98:55751] (udp) / 'airable.wifiradiofrontier.com.' (A)
radio_dns        | 2025-01-15 10:41:25 [DNSHandler:Resolver] Reply: [192.168.10.98:55751] (udp) / 'airable.wifiradiofrontier.com.' (A) / RRs: A
```

I can confirm that the container properly resolves:
```
root@radio-api:/datas/radio-api# dig +short airable.wifiradiofrontier.com @127.0.0.1
192.168.10.134
root@radio-api:/datas/radio-api# dig +short hama.wifiradiofrontier.com @192.168.10.134
192.168.10.134
```

Any ideas what the issue could be ?
